server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:h2:~/bms
    username: hegx
    password: 123456
  h2:
    console:
      enabled: true
#mybatis:
#mapper-locations: classpath:mapper/*Mapper.xml
#type-aliases-package: com.szhn.hegx.bms

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.szhn.hegx.bms.modle

#showSql
logging:
  level:
    com:
      example:
        mapper : INFO