server:
  port: 8080

# DataSource Config
spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: hegx
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    jpa:
      database: h2
      hibernate:
        ddl-auto: update
      show-sql: true
      h2:
        console:
          path: /h2-console
          enabled: true
#mybatis:
mapper-locations: classpath:mapper/*Mapper.xml
type-aliases-package: com.szhn.hegx.bms

#showSql
logging:
  level:
    com:
      example:
        mapper : debug